use crate::beam::oscilloscope::Waveform;
use crate::types::OscilloscopeState;

use std::f32::consts::{FRAC_PI_2, FRAC_PI_4};

pub struct OscilloscopePreset {
    pub name: &'static str,
    pub description: &'static str,
    pub state: OscilloscopeState,
}

pub const OSCILLOSCOPE_PRESETS: &[OscilloscopePreset] = &[
    OscilloscopePreset {
        name: "Circle",
        description: "Classic Lissajous 1:1",
        state: OscilloscopeState {
            x_waveform: Waveform::Sine,
            x_frequency: 100.0,
            x_amplitude: 0.4,
            x_phase: 0.0,
            x_dc_offset: 0.0,
            y_waveform: Waveform::Sine,
            y_frequency: 100.0,
            y_amplitude: 0.4,
            y_phase: FRAC_PI_2,
            y_dc_offset: 0.0,
            sample_rate: 44100.0,
        },
    },
    OscilloscopePreset {
        name: "Figure Eight",
        description: "Lissajous 1:2",
        state: OscilloscopeState {
            x_waveform: Waveform::Sine,
            x_frequency: 100.0,
            x_amplitude: 0.4,
            x_phase: 0.0,
            x_dc_offset: 0.0,
            y_waveform: Waveform::Sine,
            y_frequency: 200.0,
            y_amplitude: 0.4,
            y_phase: 0.0,
            y_dc_offset: 0.0,
            sample_rate: 44100.0,
        },
    },
    OscilloscopePreset {
        name: "Trefoil",
        description: "Lissajous 2:3",
        state: OscilloscopeState {
            x_waveform: Waveform::Sine,
            x_frequency: 200.0,
            x_amplitude: 0.4,
            x_phase: FRAC_PI_4,
            x_dc_offset: 0.0,
            y_waveform: Waveform::Sine,
            y_frequency: 300.0,
            y_amplitude: 0.4,
            y_phase: 0.0,
            y_dc_offset: 0.0,
            sample_rate: 44100.0,
        },
    },
    OscilloscopePreset {
        name: "Star",
        description: "Lissajous 3:4",
        state: OscilloscopeState {
            x_waveform: Waveform::Sine,
            x_frequency: 300.0,
            x_amplitude: 0.4,
            x_phase: 0.0,
            x_dc_offset: 0.0,
            y_waveform: Waveform::Sine,
            y_frequency: 400.0,
            y_amplitude: 0.4,
            y_phase: 0.0,
            y_dc_offset: 0.0,
            sample_rate: 44100.0,
        },
    },
    OscilloscopePreset {
        name: "Bow Tie",
        description: "Infinity shape",
        state: OscilloscopeState {
            x_waveform: Waveform::Sine,
            x_frequency: 100.0,
            x_amplitude: 0.4,
            x_phase: 0.0,
            x_dc_offset: 0.0,
            y_waveform: Waveform::Sine,
            y_frequency: 200.0,
            y_amplitude: 0.4,
            y_phase: FRAC_PI_2,
            y_dc_offset: 0.0,
            sample_rate: 44100.0,
        },
    },
    OscilloscopePreset {
        name: "Diamond",
        description: "Rectangular trace",
        state: OscilloscopeState {
            x_waveform: Waveform::Square,
            x_frequency: 100.0,
            x_amplitude: 0.4,
            x_phase: 0.0,
            x_dc_offset: 0.0,
            y_waveform: Waveform::Square,
            y_frequency: 100.0,
            y_amplitude: 0.4,
            y_phase: FRAC_PI_2,
            y_dc_offset: 0.0,
            sample_rate: 44100.0,
        },
    },
    OscilloscopePreset {
        name: "Spiral",
        description: "Slowly rotating fill",
        state: OscilloscopeState {
            x_waveform: Waveform::Sine,
            x_frequency: 100.0,
            x_amplitude: 0.4,
            x_phase: 0.0,
            x_dc_offset: 0.0,
            y_waveform: Waveform::Sine,
            y_frequency: 100.5,
            y_amplitude: 0.4,
            y_phase: FRAC_PI_2,
            y_dc_offset: 0.0,
            sample_rate: 44100.0,
        },
    },
    OscilloscopePreset {
        name: "Sawtooth Weave",
        description: "Complex weave pattern",
        state: OscilloscopeState {
            x_waveform: Waveform::Sawtooth,
            x_frequency: 100.0,
            x_amplitude: 0.4,
            x_phase: 0.0,
            x_dc_offset: 0.0,
            y_waveform: Waveform::Sawtooth,
            y_frequency: 150.0,
            y_amplitude: 0.4,
            y_phase: 0.0,
            y_dc_offset: 0.0,
            sample_rate: 44100.0,
        },
    },
    OscilloscopePreset {
        name: "Dot",
        description: "Focused beam spot",
        state: OscilloscopeState {
            x_waveform: Waveform::Sine,
            x_frequency: 100.0,
            x_amplitude: 0.0,
            x_phase: 0.0,
            x_dc_offset: 0.0,
            y_waveform: Waveform::Sine,
            y_frequency: 100.0,
            y_amplitude: 0.0,
            y_phase: 0.0,
            y_dc_offset: 0.0,
            sample_rate: 44100.0,
        },
    },
];
